controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_article:
    path: /article/{id}
    controller: 'App\Controller\PublicController::article'

app_commentaires_create:
    path: /commentaires/create
    controller: App\Controller\CommentairesController::create
    methods: ['POST']